#!/usr/bin/env bash

HERE=`dirname $0`
NOW=`date "+%Y-%m-%d %H:%M:%S"`

git pull \
  && $HERE/rename_with_uid -i "obsidian/box" \
  && git add . \
  && git commit -m "Quartz sync: $NOW" \
  && git push

